apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pbdd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pbdd
    app.kubernetes.io/part-of: test-app-tavd
  name: test-component-pbdd
  namespace: build-e2e-nxwb-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-pbdd
status:
  loadBalancer: {}
